#!/usr/bin/env python3
"""Generate LaTeX macros directly from the validated summary table."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, required=True)
    parser.add_argument("--out", type=Path, default=Path("docs/report/generated_numbers.tex"))
    args = parser.parse_args()
    frame = pd.read_csv(args.summary)
    completed = int((frame.get("status", pd.Series(dtype=str)) == "completed").sum())
    failed = len(frame) - completed
    source_commits = frame["source_commit"].dropna().nunique() if "source_commit" in frame else 0
    text = (
        "% Generated by docs/numbers.py; do not edit.\n"
        f"\\newcommand{{\\TotalRuns}}{{{len(frame)}}}\n"
        f"\\newcommand{{\\CompletedRuns}}{{{completed}}}\n"
        f"\\newcommand{{\\NonCompletedRuns}}{{{failed}}}\n"
        f"\\newcommand{{\\SourceCommitCount}}{{{source_commits}}}\n"
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text, encoding="utf-8")
    print(args.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
